# Usa la imagen base de Node.js 16
FROM node:16

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia todos los archivos del proyecto al directorio de trabajo del contenedor
COPY . .

# Expone el puerto 4200 para acceder a la aplicación Angular
EXPOSE 4200

# Comando predeterminado para ejecutar la aplicación Angular
CMD ["npm", "start"]
